### ISSUE TITLE
QT5 issue

### ISSUE THREAD

**Issue by Nikomaru** [Maldela/fancontrol-gui#4] opened 2016-10-16 15:36 UTC
I just installed this and tested it out. Looks great, but I wanted to change the graph range. After loading the program again from terminal, went to edit the box and got this error:

"Temp has no label: \"/sys/devices/virtual/hwmon/hwmon0/temp1\""
"Temp has no label: \"/sys/devices/virtual/hwmon/hwmon0/temp2\""
file:///usr/lib/qt/qml/QtQuick/Controls/ToolBar.qml:147:9: QML Item: Binding loop detected for property "layoutHeight"
file:///usr/lib/qt/qml/QtQuick/Controls/ToolBar.qml:147:9: QML Item: Binding loop detected for property "layoutHeight"
file:///usr/share/kpackage/genericqml/fancontrol-gui/contents/ui/Application.qml:65:14: QML ToolBar: Binding loop detected for property "implicitHeight"
**file:///usr/lib/qt/qml/QtQuick/Controls/SpinBox.qml:311:20: QML SpinBoxValidator: Binding loop detected for property "value"**

Clicking the arrows on the spinner change the value in what looks like algorithmic doubles. Clicking the text box itself does nothing until I try to enter a value, at which point it provides the error well more than 150 times before the program crashes out ungracefully with "Segmentation Fault"

Is there possibly a config file somewhere I can edit? Do I need another dependency loaded? Should I turn it off and on again?

**Comment by Maldela** [comment] 2016-10-16 16:00
I can't reproduce your spinbox error. Which Qt version are you using? Are you using Celsius or Fahrenheit?
There is a config file in ~/.config/fancontrol-gui where you can edit these values directly.
A sample file could look like this:

[preferences]
MaxTemp=80
MinTemp=24

The label errors are just debug messages from fancontrol-gui. Don't worry about those. The other binding loop errors appeared when i switched to a qml plugin instead of plain qml files. But everything kept working for me so i did not investigate those.

**Comment by Maldela** [comment] 2016-10-16 16:20
I just switched to Fahrenheit and got the same errors as you. Working on a fix now.

**Comment by Maldela** [comment] 2016-10-16 16:40
Should be fixed now.

**Comment by Nikomaru** [comment] 2016-10-16 16:48
Yeah, sorry, normally my system runs Celsius, but these reading were all in Fahrenheit. Which is fine, but I didn't set anything to do that.

Thanks!

Hey, I'm noticing the graph is reading the scale legends as fahrenheit, then displaying celcius readings at the dot with F instead. Sorry to nitpick.  [image](http://imgur.com/ERnvtXW)

**Comment by Maldela** [comment] 2016-10-16 16:50
I'll have a look at that tomorrow. My laptop doesn't have any controllable fans so i can't test any changes I make while on the go.

**Comment by Nikomaru** [comment] 2016-10-16 16:52
Understood. Thanks again for the quick fix.

**Comment by Maldela** [comment] 2016-10-16 16:54
Btw the unit is chosen at program launch based on the locale reported by Qt. If you want to choose to Celsius you need to change your locale settings and restart fancontrol-gui.

**Comment by Maldela** [comment] 2016-10-17 15:05
I've reworked the tooltips. Should be fixed now.

**Closed** 2017-12-06 14:31 UTC
